name: gis_maps_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  another_flushbar: ^1.12.30
  auto_route: ^10.0.1
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  dartz: ^0.10.1
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.2
  flutter_spinkit: ^5.2.1
  freezed_annotation: ^3.0.0
  get_it: ^8.0.2
  google_fonts: ^6.2.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  loader_overlay: ^5.0.0
  logger: ^2.4.0
  shared_preferences: ^2.3.2
  sizer: ^3.0.4
  skeletonizer: ^1.4.2
  url_launcher: ^6.3.1
  faker: ^2.2.0
  iconsax_plus: ^1.0.0
  smooth_page_indicator: ^1.0.0
  google_generative_ai: ^0.4.7
  mime: ^2.0.0
  hive: ^2.2.3
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5
  google_maps_flutter: ^2.12.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.0
  http: ^1.1.0
  geojson_vi: ^2.2.5
  csv: ^6.0.0
  collection: ^1.18.0
  flutter_map_geojson: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^10.0.1
  bloc_test: ^10.0.0
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.1
  freezed: ^3.0.6
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0
  flutter_lints: ^5.0.0
  syncfusion_flutter_charts: ^29.1.38
  flutter_document_picker: ^5.2.3

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/core/
